version: '2'
services:
  app:
    extends:
      file: services.yml
      service: app
    image: app:<%= @stand.short_reference %>
    volumes_from:
      - data
    depends_on:
      - data
    ports:
      - 10080:80
  data:
    image: data:<%= @stand.short_reference %>
    extends:
      file: services.yml
      service: data