version: '2'
services:
  app:
    extends:
      file: services.yml
      service: app
    volumes_from:
      - data
  data:
    extends:
      file: services.yml
      service: data
  nginx:
    extends:
      file: services.yml
      service: nginx
  db:
    extends:
      file: services.yml
      service: db
    volumes_from:
      - data
    depends_on:
      - data
