version: '2'
services:
  app:
    extends:
      file: services.yml
      service: app
    image: app:<%= @stand.short_reference %>
    volumes_from:
      - data
    depends_on:
      - data
  data:
    extends:
      file: services.yml
      service: data
