version: '2'
services:
  app:
    extends:
      file: services.yml
      service: app
    image: <%= @stand.project.docker_repo %>_app_<%= @stand.short_reference %>
    volumes_from:
      - data
    depends_on:
      - data
  data:
    image: <%= @stand.project.docker_repo %>_data_<%= @stand.short_reference %>
    extends:
      file: services.yml
      service: data