source 'https://rubygems.org'
ruby '2.3.1'

gem 'rails', '4.1.5'

gem 'pg'
gem 'rails_12factor'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.3'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes

gem 'jquery-rails'
gem 'turbolinks'
gem 'underscore-rails'

gem 'puma'

gem 'bootstrap-sass'
gem 'jquery-turbolinks'

gem 'tzinfo-data', platforms: [:mingw, :mswin]